name: sortQL CI/CD

on: [push, pull_request]

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: bun test
